### ISSUE TITLE
Built file not included when installing from npm

### ISSUE THREAD

**Issue by brentoneill** [mu29/react-radio-buttons#3]
When installing this package from npm via `npm install react-radio-buttons`, the built files that the package.json is looking for, `lib/index.js`, is not included because the dir `lib` is included in the `.gitignore`. This means that currently, the README.md instructions are incorrect.

To generate this `lib/index.js` file, you have to go in to this package dir and run `npm run build-cjs`. This means the package as a whole is not "ready to use" right when you install.

Typically with NPM packages, you include the built file and tag a release.

My suggestion is simply to remove `lib` from the `.gitignore` and run a build to generate the file and commit both changes to the repo.

**Comment by brentoneill** [comment]
PR - https://github.com/mu29/react-radio-buttons/pull/4

**Comment by mu29** [comment]
Thanks a lot!
I have to run prerelease command and then deploy it, but I forgot it some time.
Your solution seems to be better :)
