### ISSUE TITLE
Wrong propTypes 

### ISSUE THREAD

**Issue by konekoya** [mu29/react-radio-buttons#5]
Hi @mu29,

I'm using your package in my project and have come across a few weird React warnings in Chrome devTools. After a couple of searches. It turned out that you're using[ wrong prop type check in your code](https://github.com/mu29/react-radio-buttons/blob/master/lib/index.js#L210). As in [this issue discuss](https://github.com/matthewwithanm/react-controllables/issues/5#issuecomment-234296403). Could you fix it :) Thank you!

**Comment by mu29** [comment]
Fixed [here](https://github.com/mu29/react-radio-buttons/commit/ee0943ddc8fb647134a5b850f0860a7044d4211d), and I just released a new version.
Thank you!

**Comment by konekoya** [comment]
Great! Thanks for the quick update. really appreciate your hard work!

**Comment by Dimon70007** [comment]
Thanks. It was very helpfull.
